ECHO OFF
@ECHO OFF
C:
CD\
CD C:\Users\Sduibek\Documents\Dropbox\Fallout\Scripts-editing
IF ERRORLEVEL 1 PAUSE
IF EXIST V13CAVE.INT del V13CAVE.INT
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13CAVE.SSL
IF ERRORLEVEL 1 PAUSE
MOVE /Y V13CAVE.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\V13CAVE.INT
IF ERRORLEVEL 1 PAUSE
