ECHO OFF
@ECHO OFF
C:
CD\
CD C:\Users\Sduibek\Documents\Dropbox\Fallout\Scripts-editing
IF ERRORLEVEL 1 PAUSE
IF EXIST OBJ_DUDE.INT del OBJ_DUDE.INT
IF ERRORLEVEL 1 PAUSE
sslc_f1 OBJ_DUDE.SSL
IF ERRORLEVEL 1 PAUSE
MOVE /Y OBJ_DUDE.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\OBJ_DUDE.INT
IF ERRORLEVEL 1 PAUSE
