ECHO OFF
@ECHO OFF
C:
CD\
CD C:\Users\Sduibek\Documents\Dropbox\Fallout
IF ERRORLEVEL 1 PAUSE
DEL log.txt
IF ERRORLEVEL 1 PAUSE
f2wedit.exe
IF ERRORLEVEL 1 PAUSE
TIMEOUT /T 3
IF ERRORLEVEL 1 PAUSE
DEL log.txt
IF ERRORLEVEL 1 PAUSE
