ECHO OFF
@ECHO OFF
C:
CD\
CLS
CD C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\MAPS
IF ERRORLEVEL 1 PAUSE
IF EXIST AUTOMAP.DB del AUTOMAP.DB
IF ERRORLEVEL 1 PAUSE
DEL *.SAV
IF ERRORLEVEL 1 PAUSE
ECHO.
CD C:\Users\Sduibek\Documents\Dropbox\Fallout\Scripts-editing
IF ERRORLEVEL 1 PAUSE
DEL *.INT /Q
IF ERRORLEVEL 1 PAUSE
sslc_f1 OBJ_DUDE.SSL
IF ERRORLEVEL 1 PAUSE
move /Y OBJ_DUDE.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\OBJ_DUDE.INT
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 V13CAVE.SSL
IF ERRORLEVEL 1 PAUSE
move /Y V13CAVE.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\V13CAVE.INT
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 IRWIN.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 GENDISK.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 SOPDISK.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 MAXDISK.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 DISKA.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 DISKD.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 HUBMIS0.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 HUBDWNTN.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 VREEDISK.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 VREE.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 ARTIFACT.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 FEVDISK.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 SECDISK.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 REGDISK.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 RAZOR.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 VDOORMUT.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 JON.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 DOORCODE.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 CABBOT.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 VALTDISK.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
REM -------------------------------------------------------------------------------------
REM	IF EXIST STRANGER.INT del STRANGER.INT
REM	sslc_f1 STRANGER.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y STRANGER.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\STRANGER.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST HUBENCTR.INT del HUBENCTR.INT
REM	sslc_f1 HUBENCTR.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y HUBENCTR.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\HUBENCTR.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST CARVLEAD.INT del CARVLEAD.INT
REM	sslc_f1 CARVLEAD.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y CARVLEAD.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\CARVLEAD.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST COW.INT del COW.INT
REM	sslc_f1 COW.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y COW.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\COW.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST HUNTER.INT del HUNTER.INT
REM	sslc_f1 HUNTER.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y HUNTER.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\HUNTER.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST CARENCTR.INT del CARENCTR.INT
REM	sslc_f1 CARENCTR.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y CARENCTR.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\CARENCTR.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST RAIDGRD.INT del RAIDGRD.INT
REM	sslc_f1 RAIDGRD.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y RAIDGRD.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\RAIDGRD.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST GWEN.INT del GWEN.INT
REM	sslc_f1 GWEN.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y GWEN.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\GWEN.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	rem Script Error: scripts\Killian.int: op_move_obj_inven_to_obj: obj is NULL
REM	
REM	IF EXIST KILLIAN.INT del KILLIAN.INT
REM	sslc_f1 KILLIAN.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y KILLIAN.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\KILLIAN.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	rem Script Error: scripts\Killian.int: op_move_obj_inven_to_obj: obj is NULL
REM	
REM	IF EXIST JUNKKILL.INT del JUNKKILL.INT
REM	sslc_f1 JUNKKILL.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y JUNKKILL.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\JUNKKILL.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST KILLSTOR.INT del KILLSTOR.INT
REM	sslc_f1 KILLSTOR.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y KILLSTOR.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\KILLSTOR.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST THUG.INT del THUG.INT
REM	sslc_f1 THUG.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y THUG.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\THUG.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST JEREM2.INT del JEREM2.INT
REM	sslc_f1 JEREM2.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y JEREM2.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\JEREM2.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST KALNOR.INT del KALNOR.INT
REM	sslc_f1 KALNOR.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y KALNOR.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\KALNOR.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST GENRAIDR.INT del GENRAIDR.INT
REM	sslc_f1 GENRAIDR.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y GENRAIDR.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\GENRAIDR.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST RAIDMAP.INT del RAIDMAP.INT
REM	sslc_f1 RAIDMAP.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y RAIDMAP.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\RAIDMAP.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
REM	IF EXIST KLAXON.INT del KLAXON.INT 
REM	sslc_f1 KLAXON.SSL
REM	IF ERRORLEVEL 1 PAUSE
REM	move /Y KLAXON.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\KLAXON.INT
REM	IF ERRORLEVEL 1 PAUSE
REM	
MOVE /Y *.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS
IF ERRORLEVEL 1 PAUSE
CD C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\PROTO
IF ERRORLEVEL 1 PAUSE
ATTRIB -S -H /D /S *.*
IF ERRORLEVEL 1 PAUSE
ATTRIB -A +R /S *.PRO
IF ERRORLEVEL 1 PAUSE
CD C:\Users\Sduibek\Documents\Dropbox\Fallout
IF ERRORLEVEL 1 PAUSE
set DEBUGACTIVE=LOG
IF ERRORLEVEL 1 PAUSE
FalloutW.exe
