ECHO OFF
@ECHO OFF
C:
CD\
CLS
CD C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\MAPS
IF ERRORLEVEL 1 PAUSE
IF EXIST AUTOMAP.DB del AUTOMAP.DB
IF ERRORLEVEL 1 PAUSE
DEL *.SAV
IF ERRORLEVEL 1 PAUSE
ECHO.
CD C:\Users\Sduibek\Documents\Dropbox\Fallout\Scripts-editing
IF ERRORLEVEL 1 PAUSE
DEL *.INT /Q
IF ERRORLEVEL 1 PAUSE
sslc_f1 OBJ_DUDE.SSL
IF ERRORLEVEL 1 PAUSE
move /Y OBJ_DUDE.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\OBJ_DUDE.INT
IF ERRORLEVEL 1 PAUSE
ECHO.
sslc_f1 V13CAVE.SSL
IF ERRORLEVEL 1 PAUSE
move /Y V13CAVE.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS\V13CAVE.INT
IF ERRORLEVEL 1 PAUSE
ECHO.
CD C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\PROTO
IF ERRORLEVEL 1 PAUSE
ATTRIB -S -H /D /S *.*
IF ERRORLEVEL 1 PAUSE
ATTRIB -A +R /S *.PRO
IF ERRORLEVEL 1 PAUSE
CD C:\Users\Sduibek\Documents\Dropbox\Fallout
IF ERRORLEVEL 1 PAUSE
set DEBUGACTIVE=GNW
IF ERRORLEVEL 1 PAUSE
FalloutW.exe
