@ECHO OFF
ECHO OFF
C:
CD\
CD C:\Users\Sduibek\Documents\Dropbox\GitHub\fixtsrc\SCRIPTS
IF ERRORLEVEL 1 PAUSE
DEL *.INT /Q
IF ERRORLEVEL 1 PAUSE
DEL *.BAK /Q
IF ERRORLEVEL 1 PAUSE
DEL *.INT /Q
IF ERRORLEVEL 1 PAUSE
rem
rem Testing for Mike's save, SLOT09 that crashes in combat:
rem
sslc_f1 MONSTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASTER1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASTER2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLINVAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AIRGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AIRGRD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 IAN.SSL
IF ERRORLEVEL 1 PAUSE
rem
rem
rem
sslc_f1 IRWIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSLORRI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TEST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBMIS0.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBDWNTN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARTIFACT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CABBOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VLASER.SSL
IF ERRORLEVEL 1 PAUSE
ECHO.
ECHO.
sslc_f1 RNDCOAST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOGMEAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOG2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOG.SSL
IF ERRORLEVEL 1 PAUSE
rem	ECHO.
rem	ECHO.
rem	sslc_f1 RNDCITY.SSL
rem	IF ERRORLEVEL 1 PAUSE
rem	ECHO.
rem	ECHO.
rem	sslc_f1 RNDMTN.SSL
rem	IF ERRORLEVEL 1 PAUSE
rem	ECHO.
rem	ECHO.
rem	sslc_f1 RNDDESRT.SSL
rem	IF ERRORLEVEL 1 PAUSE
rem	ECHO.
rem	ECHO.
rem	sslc_f1 RNDCOAST.SSL
rem	IF ERRORLEVEL 1 PAUSE
rem	ECHO.
MOVE /Y *.INT C:\Users\Sduibek\Documents\Dropbox\Fallout\DATA\SCRIPTS
IF ERRORLEVEL 1 PAUSE
