@ECHO OFF
ECHO OFF
C:
CD\
CD C:\Users\Sduibek\Documents\Dropbox\GitHub\fixtsrc\SCRIPTS
IF ERRORLEVEL 1 PAUSE
DEL *.INT /Q
IF ERRORLEVEL 1 PAUSE
DEL *.BAK /Q
IF ERRORLEVEL 1 PAUSE
DEL *.INT /Q
IF ERRORLEVEL 1 PAUSE
sslc_f1 1DEDGUL1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 1LADDER1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 1MANHOL1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 1MOLERAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 1MOLRAT1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ABEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADY2CELL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADY2FARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADY2STOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADYSTORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADYTOWNR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AGATHA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AGATHBED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AIRGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AIRGRD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AIRLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALEX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALLDOGS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALLNONE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALPHHOTL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALYA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AMBER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ANDREW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ANIMFRVR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ANIMFR~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARADESH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARMDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARMOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARMORY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARMSDEAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARTIFACT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ASSBLOW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AVERY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BAKA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARFLY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARRACUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARSTOW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARTERGU.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARTERGY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARTER~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BASIC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BECA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BETHBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BETHGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BHDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BILL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BILLY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BITSBOB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLADE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLADES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLAST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLKROM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLKROOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOBSIGN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOBSTAND.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BONEBODY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOOKCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSASIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSASIST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSDOCTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSLORI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSLORRI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOXGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BRAHMIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BRENDEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BRODEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROHD12.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROHD34.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROHDENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROHIST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROINVAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BULLBORD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BUTCH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BV2VAULT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVAIR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVAIRL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVBROKEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVCACHE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVCORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELEV1W.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELV1W.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELV2E.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELV2W.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELV3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVLAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVLIB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVLIVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVMEET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVSTORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BYCHRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BYGREG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BYMIKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CABBOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CALDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CALEB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CALLY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CARCOW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CARCUST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CARENCTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CARVLEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CATH2MV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CATHCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CATHSHOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CAVE2V13.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CAVEWALL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CBLKDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCGUARD1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCGUARD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCRTNVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCVAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CELL2ADY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHAIR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHANTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHARBODY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHDGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHDSCOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHEATER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHEPSLOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHID2MAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHID2TWR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHIDGAB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHIDINIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHIDNITE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHIDSCOL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDMEM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDRN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDRN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHITEM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDR~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHOCDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHOCTECH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHUCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CINDY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CITIZEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CLEO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CLOCKMAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COCDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CODEDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COLATRUK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COMMAND.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COMPTROL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COMPUTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COOK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COOKSHEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COOKTABL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CORECOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COUGAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COVER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COYOTE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CPRAY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRASHBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRASHRM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CREDDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRVNDRVR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRVNENMY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRVNMSTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRVNTEAM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CR_DIALG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CTOWER1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CTOWER2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CTOWER3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CURTIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DANE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DANWIFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DARREL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DCMUTANT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEADBRO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEADCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEADGUY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEALER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEATHSPR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DECKER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DECKGARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DECKGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEFINE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMETRE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOCRYP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMODOG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMODOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOFOOL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOGEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOPEAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOPHIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DESERT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DETHCAVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DETHCLAW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DIANA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DIRTNAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DISKA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DISKD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOCLOCKR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOCWU.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOG2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOGMEAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOLGAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DONOTUSE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOORCODE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DRAGON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DRWHOMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DUC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DUGAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DUMAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EDEBRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EGGCLAW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELCTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELECDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELECTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV0.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV10.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV11.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV6.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV6_M1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV7.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV9.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEVATR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEVCON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER1A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER1B.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER1C.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER1D.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER2A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER2B.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER2C.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER3A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER4A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER5A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER6A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITERH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ENEMY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EXITBASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EXITLITE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FALCON1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARLI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARM2ADY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMPART.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD6.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD7.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FEARDARK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FEMFARMR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FEVDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FGTCARVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FGTGARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FGTRTNVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FGTVAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD1A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD1B.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD1C.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD1D.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD2A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD2B.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD2C.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD34.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD3A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD4A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD5A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD6A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDGEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIRE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FISHRMAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FISHRSON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FKE_DUDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLARE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLASH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLIP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLOATER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLSUPMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLDN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLINIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLINVAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLLMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLSCHOL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLSCOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLUP2DN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOOTMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOOTPRNT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FORCCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FORCECON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRANCIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FREEZER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRIDG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRIDGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRMRAID1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRUIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRYSTUB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FSAUSER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GABRIEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GAMBLER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GANGER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GAR2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GARL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GARRET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GARY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GASTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GATEDEMO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENBCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENCHANT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENCHAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENCOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENEMIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENERIC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENFGT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGAMBL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGHOUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGLOW1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGRDA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGRDB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGRDC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENINIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENINT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENKNIGH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENMERCA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENMERCB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENMERCC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENMUTAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPALA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPALAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPALB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPALC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAID2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAIDA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAIDB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAIDC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAIDR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSARG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSCRIB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSKAG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSKULZ.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSUPR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENT2LV1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENVAULT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GET2LEV1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHDEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHDORGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHGENDED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHKICK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHMAIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHOUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHREFUGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHRNDGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHTEMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHZERO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GIDEON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GIZGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GIZMO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO1WEAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO3SUPL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO3WEP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO4SUPL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO4WEAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOBLDOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOBLELV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOCABN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLORDDOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOW4W~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWCAGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWDESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWGEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWGN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWMAP1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWMAP2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWONE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWPUMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWTABL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOYLDOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLV12ENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLWALIEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLWBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GOODSLOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GPWRTERM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GRAFFITI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GRETCH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GRNFARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GRNMTARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GROUNDR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GSENROB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUARD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUARDEMO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUIDO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNCACHE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNRNR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNRUNR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNTHER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUSTOFER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GWEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HALL2MTL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HALL2SHD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HALLDED1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HALLGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HAROLD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HARRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HBETH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HBODGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HBODGRD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCARAVN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCARAVN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCARAVN3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCARAVN4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCHDGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HDEALER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HDTDN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HDTUP2DN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HDTVAULT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HEATHER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENCVAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENDEAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENFARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENGAMB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENVAN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HHOOKERA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HHOOKERD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HHOOKER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HHOOKER2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HICRAPS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HIGHELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HIGHJACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HIGHTOWR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HJOHN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HORD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOSTILE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOTELMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOTGHOUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOTSPOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOUSCHAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HRNDBAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HROULET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HSLOTS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRGRGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRLEON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRRICK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRWIFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBBER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBCAPTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBCARVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBCOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBDWNTN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBENCTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBFLRCD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBHEIGT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBJAKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBMIS0.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBMIS1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBOLDTN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBPATNT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBSAFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBSMITY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBWATER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUNTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HWMHOST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 IAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ICECHEST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ICEPICK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 INBLADE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 INITIATE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 INVADED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 INVADER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 IRWIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ISMARC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 IZO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JAIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JAKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JAKEDESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JAKEDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JARIV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JARVIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JASMINE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JASON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JBOXER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JCAS2KIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JCHIDMEM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JENNIFER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JENT2KIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JEREM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JEREM2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JKIL2CAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JKIL2ENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JNKSCOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JOBPOST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JOHN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JONATHAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTBOB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTCHIDME.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTDN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTGENGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTILE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTPEASNT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTRAIDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTUP2DN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JULIANNA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKCAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKDEMO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKDOG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKIE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKJAIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKKILL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKPEAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUSTIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KALNOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KANE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KANEDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KATJA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KENJI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KENNY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KERI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILDOOR1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILDOOR2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILLIAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILLSAFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILLSTOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KLAXON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KNIGHTA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KNIGHTB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KRUPPER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KYLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAADYTUM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LABLADES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LADDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAFOLLWR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAGUNRUN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LANCE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LARIPPER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LARRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LARS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LARYKNIG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LASHER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAURA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAZRTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LEADER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LEMMY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LENNY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LENORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LEON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LEX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LGFTPRNT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LIBCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LIBRARY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LITELEAV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LIVINGQ.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOCKER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LONERAID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOOKOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORENZO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRAINE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRIAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRIANE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRAINE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOSER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOWCRAPS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOWJACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOXLEY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LTCODES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LTGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LUCY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LUKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LYLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MACHIV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MACRAE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MADBROT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MADSCI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MANAGER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MANGLED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MANHOLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MANTIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAP_INIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MARCELLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MARCEL~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MARNEY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAS2CHID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASSACRE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASTER1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASTER2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MATHIA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAXDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAXGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAXSON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAXSON2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBDEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBOUT2IN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBSTRONG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBVATS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MEANDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MEDIC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MEDLAB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MEETING.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MERCH1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 METLDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MICHAEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MICHAE~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MICHELLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MIKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MILES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MISSBRO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MITCHBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MLOPS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MLPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MLPRISON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOATCHEK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOATGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MODREACT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOLERAT2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOMCLAW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MONSTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MORBCOOL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MORBID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MORPCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MORPH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOTEL2HL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MRHANDYA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MRHANDYB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MRHANDYC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MSTMERCH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MSTRCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTAMBSH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTANT2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTANT3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTANT4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTANT5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTEJAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTFRUIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVAIRLOC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVBSHELF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVDWN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVNEWS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVNUKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVRCRDOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVSCTSHF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVUP2DWN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MYSTSTRN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NDEBRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NDWN2UP1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NDWN2UP2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NEAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NECVHOLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NECVLADR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NEIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NGARFRDG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NH2OCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NH2OPUMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHAL2HOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHAL2WAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHAL4HOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHAL4WAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHDN2UP1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHDN2UP2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHDN2UP3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHOT2HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHOT4HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHUP2DN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHUP2DN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHUP2DN3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NICOLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NUKEGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NUP2DWN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NUP2DWN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWAT2HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWAT4HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWDN2UP1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWDN2UP2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWDN2UP3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWUP2DN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWUP2DN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWUP2DN3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 OBJ_DUDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ODDWALL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 OFFICER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ORFEO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 OVER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 OVERSEE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 P.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PAINFELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALADINA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALADINB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALADINC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALSCOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PATRICK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PAUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PEASANTC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PEASANTD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PEASVICT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PENSMELL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PERNPWR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PETER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PETROX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PEZ.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PHIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PHRAX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PLEASANT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 POWERMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PRISCON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PRISFELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PRISON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PRISONR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PSYCON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PSYFIELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADIO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADIOCOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADRAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADSCAVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADSCOR2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADSCORP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAIDDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAIDGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAIDMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAIDPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RATION.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RATPIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAYZE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAZLO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAZOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RD1INIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RD1KNIG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RD1SCB1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RD1SCRB1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REBEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REDFARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REDFIELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REGDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REGGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REGULATR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REVULSE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RHOMBUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RHOMDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RHOMLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RICHIE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RIPDN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RIPPER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RIPPPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RIPUP2DN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RN1SCRB1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDCITY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDCOAST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDDERT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDDESRT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDESRT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDECGEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDECSPL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDMERCH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDMTN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROAMCLAW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROBCTRL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROBOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROMERO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROOMGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROPE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROZBED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUBCHIP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUBCORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUFUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUTGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUTGER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SALLY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SAMMAEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SAMMY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SAMMY2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SARAH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SAUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SBOKCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCHOLAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCIROOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCOUTC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCOUTF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCRIBEA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCRIBEB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCRIBEC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCSUPMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SDEBRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SDRESSER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SECDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SECDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SEMICOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SENTRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SENTRYGN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SEST2WST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETCOLER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETDESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETDOOR1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETH2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETSCTDR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SGENROB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHADDESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHADYET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHADYRUG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHADYWST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHARK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHED2HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHERRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SINK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SINTHIA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SKIPPY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SKIZZER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SKUMDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SLAPPY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SLUMMER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMELL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMITTY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMONE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMPRAY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMTWO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SOPDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SOPHIA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SPAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SPOTLITE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SSGUIDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SSRADSCO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SSWELL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STAMPEDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STAPBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STAPLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STIMPACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STOR2ADY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STOREROM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STRANGER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STUDENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STUFF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPAMBSH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPLYGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SURF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SWST2EST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TALIUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TALKCOW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TALKCOWS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TALUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TANDI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TARDIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TAYLOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TCOWMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TEACHER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TEMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM6.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM7.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM8.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TEST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TESTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THERESA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THFD2U.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THFU2D.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THOMAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THOMAS2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THORNDYK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THSUPMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THUG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TOGGLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TOLYA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TOW2CHID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TOWNMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TRAPFLOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TREAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TRENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TRISH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TROPHY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TROY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TYCHO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TYLIER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 UNDRBED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 USEDCAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 UTHERN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 UZCHAIR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V132CAVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13CAVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13CAVES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13COMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13DOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALEL1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALEL2E.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALEL2W.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALEL3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTCORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTCTZN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTCUPL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTGLO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTLEAV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTMED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTMEET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTMON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTNEC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTSEC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTSTOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VANCE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VANCEBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VANHAG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VASQUEZ.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VATALERT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VATSIGN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VATTEAM9.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VATWARN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VAULT13.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VAULTBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VAULTBUR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VAULTENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VBOOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VBROKELV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VCOMPOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VCONCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VCONDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VDOORMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VELCTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VEXDTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VFENCEMT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VGATEMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VICTOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VINCENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VINNIE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VIOLA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VISCIOUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VLASER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VLOCKER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VMONOWIR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VPLASMA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VPLOTMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VPLSTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VREE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VREEDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VREGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VRESCRIB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VSGTEAM9.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM6.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM7.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM8.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VWEPLOKR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WANRAT2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WANRATS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WATRSHED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WDEBRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WEAPSYS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WHOMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WIFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WIGGUP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMCARVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMGROUP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMRTNVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMVAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WOMEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WOODDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WORKROOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WORLD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRHOLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRLADR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRMGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRTHIEF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 YOURROOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ZACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ZARK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ZAX.SSL
IF ERRORLEVEL 1 PAUSE
MOVE /Y *.INT C:\USERS\SDUIBEK\DOCUMENTS\DROPBOX\FALLOUT\DATA\SCRIPTS
IF ERRORLEVEL 1 PAUSE
CD Placeholders
IF ERRORLEVEL 1 PAUSE
DEL *.INT /Q
IF ERRORLEVEL 1 PAUSE
DEL *.BAK /Q
IF ERRORLEVEL 1 PAUSE
DEL *.INT /Q
IF ERRORLEVEL 1 PAUSE
sslc_f1 1DEDGUL1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 1LADDER1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 1MANHOL1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 1MOLERAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 1MOLRAT1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ABEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADY2CELL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADY2FARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADY2STOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADYSTORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ADYTOWNR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AGATHA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AGATHBED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AIRGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AIRGRD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AIRLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALEX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALLDOGS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALLNONE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALPHHOTL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ALYA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AMBER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ANDREW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ANIMFRVR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ANIMFR~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARADESH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARMDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARMOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARMORY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARMSDEAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ARTIFACT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ASSBLOW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 AVERY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BAKA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARFLY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARRACUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARSTOW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARTERGU.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARTERGY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BARTER~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BASIC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BECA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BETHBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BETHGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BHDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BILL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BILLY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BITSBOB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLADE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLADES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLAST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLKROM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BLKROOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOBSIGN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOBSTAND.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BONEBODY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOOKCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSASIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSASIST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSDOCTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSLORI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOSLORRI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BOXGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BRAHMIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BRENDEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BRODEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROHD12.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROHD34.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROHDENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROHIST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROINVAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BROLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BULLBORD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BUTCH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BV2VAULT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVAIR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVAIRL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVBROKEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVCACHE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVCORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELEV1W.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELV1W.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELV2E.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELV2W.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVELV3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVLAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVLIB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVLIVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVMEET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BVSTORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BYCHRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BYGREG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 BYMIKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CABBOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CALDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CALEB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CALLY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CARCOW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CARCUST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CARENCTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CARVLEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CATH2MV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CATHCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CATHSHOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CAVE2V13.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CAVEWALL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CBLKDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCGUARD1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCGUARD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCRTNVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CCVAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CELL2ADY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHAIR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHANTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHARBODY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHDGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHDSCOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHEATER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHEPSLOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHID2MAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHID2TWR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHIDGAB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHIDINIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHIDNITE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHIDSCOL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDMEM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDRN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDRN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHITEM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHILDR~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHOCDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHOCTECH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CHUCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CINDY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CITIZEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CLEO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CLOCKMAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COCDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CODEDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COLATRUK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COMMAND.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COMPTROL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COMPUTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COOK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COOKSHEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COOKTABL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CORECOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COUGAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COVER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 COYOTE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CPRAY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRASHBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRASHRM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CREDDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRVNDRVR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRVNENMY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRVNMSTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CRVNTEAM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CR_DIALG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CTOWER1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CTOWER2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CTOWER3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 CURTIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DANE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DANWIFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DARREL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DCMUTANT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEADBRO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEADCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEADGUY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEALER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEATHSPR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DECKER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DECKGARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DECKGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEFINE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMETRE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOCRYP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMODOG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMODOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOFOOL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOGEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOPEAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DEMOPHIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DESERT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DETHCAVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DETHCLAW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DIANA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DIRTNAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DISKA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DISKD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOCLOCKR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOCWU.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOG2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOGMEAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOLGAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DONOTUSE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DOORCODE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DRAGON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DRWHOMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DUC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DUGAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 DUMAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EDEBRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EGGCLAW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELCTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELECDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELECTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV0.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV10.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV11.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV6.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV6_M1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV7.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEV9.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEVATR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ELEVCON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER1A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER1B.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER1C.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER1D.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER2A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER2B.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER2C.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER3A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER4A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER5A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITER6A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EMITERH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ENEMY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EXITBASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 EXITLITE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FALCON1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARLI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARM2ADY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMPART.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD6.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAD7.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FARMRAID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FEARDARK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FEMFARMR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FEVDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FGTCARVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FGTGARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FGTRTNVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FGTVAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD1A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD1B.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD1C.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD1D.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD2A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD2B.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD2C.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD34.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD3A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD4A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD5A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELD6A.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDGEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIELDI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FIRE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FISHRMAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FISHRSON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FKE_DUDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLARE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLASH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLIP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLOATER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FLSUPMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLDN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLINIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLINVAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLLMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLSCHOL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLSCOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOLUP2DN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOOTMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FOOTPRNT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FORCCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FORCECON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRANCIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FREEZER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRIDG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRIDGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRMRAID1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRUIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FRYSTUB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 FSAUSER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GABRIEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GAMBLER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GANGER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GAR2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GARL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GARRET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GARY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GASTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GATEDEMO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENBCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENCHANT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENCHAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENCOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENEMIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENERIC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENFGT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGAMBL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGHOUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGLOW1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGRDA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGRDB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENGRDC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENINIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENINT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENKNIGH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENMERCA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENMERCB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENMERCC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENMUTAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPALA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPALAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPALB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPALC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAID2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAIDA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAIDB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAIDC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENRAIDR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSARG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSCRIB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSKAG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSKULZ.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENSUPR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENT2LV1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GENVAULT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GET2LEV1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHDEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHDORGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHGENDED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHKICK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHMAIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHOUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHREFUGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHRNDGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHTEMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GHZERO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GIDEON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GIZGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GIZMO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO1WEAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO3SUPL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO3WEP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO4SUPL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLO4WEAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOBLDOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOBLELV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOCABN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLORDDOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOW4W~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWCAGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWDESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWGEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWGN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWMAP1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWMAP2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWONE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWPUMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOWTABL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLOYLDOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLV12ENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLWALIEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GLWBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GOODSLOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GPWRTERM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GRAFFITI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GRETCH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GRNFARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GRNMTARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GROUNDR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GSENROB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUARD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUARDEMO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUIDO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNCACHE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNRNR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNRUNR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUNTHER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GUSTOFER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 GWEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HALL2MTL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HALL2SHD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HALLDED1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HALLGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HAROLD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HARRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HBETH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HBODGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HBODGRD2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCARAVN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCARAVN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCARAVN3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCARAVN4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HCHDGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HDEALER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HDTDN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HDTUP2DN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HDTVAULT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HEATHER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENCVAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENDEAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENFARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENGAMB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HGENVAN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HHOOKERA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HHOOKERD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HHOOKER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HHOOKER2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HICRAPS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HIGHELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HIGHJACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HIGHTOWR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HJOHN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HORD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOSTILE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOTELMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOTGHOUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOTSPOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HOUSCHAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HRNDBAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HROULET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HSLOTS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRGRGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRLEON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRRICK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HTWRWIFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBBER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBCAPTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBCARVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBCOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBDWNTN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBENCTR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBFLRCD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBHEIGT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBJAKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBMIS0.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBMIS1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBOLDTN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBPATNT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBSAFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBSMITY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUBWATER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HUNTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 HWMHOST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 IAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ICECHEST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ICEPICK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 INBLADE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 INITIATE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 INVADED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 INVADER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 IRWIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ISMARC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 IZO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JAIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JAKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JAKEDESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JAKEDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JARIV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JARVIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JASMINE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JASON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JBOXER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JCAS2KIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JCHIDMEM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JENNIFER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JENT2KIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JEREM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JEREM2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JKIL2CAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JKIL2ENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JNKSCOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JOBPOST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JOHN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JONATHAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTBOB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTCHIDME.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTDN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTGENGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTILE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTPEASNT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTRAIDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JTUP2DN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JULIANNA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKCAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKDEMO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKDOG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKIE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKJAIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKKILL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKPEAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUNKY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 JUSTIN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KALNOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KANE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KANEDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KATJA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KENJI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KENNY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KERI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILDOOR1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILDOOR2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILLIAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILLSAFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KILLSTOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KLAXON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KNIGHTA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KNIGHTB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KRUPPER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 KYLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAADYTUM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LABLADES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LADDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAFOLLWR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAGUNRUN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LANCE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LARIPPER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LARRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LARS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LARYKNIG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LASHER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAURA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LAZRTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LEADER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LEMMY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LENNY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LENORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LEON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LEX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LGFTPRNT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LIBCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LIBRARY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LITELEAV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LIVINGQ.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOCKER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LONERAID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOOKOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORENZO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRAINE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRIAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRIANE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LORRAINE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOSER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOWCRAPS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOWJACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LOXLEY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LTCODES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LTGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LUCY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LUKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 LYLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MACHIV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MACRAE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MADBROT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MADSCI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MANAGER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MANGLED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MANHOLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MANTIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAP_INIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MARCELLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MARCEL~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MARNEY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAS2CHID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASSACRE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASTER1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MASTER2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MATHIA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAXDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAXGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAXSON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MAXSON2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBDEAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBOUT2IN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBSTRONG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MBVATS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MEANDER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MEDIC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MEDLAB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MEETING.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MERCH1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 METLDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MICHAEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MICHAE~1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MICHELLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MIKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MILES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MISSBRO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MITCHBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MLOPS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MLPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MLPRISON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOATCHEK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOATGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MODREACT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOLERAT2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOMCLAW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MONSTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MORBCOOL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MORBID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MORPCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MORPH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MOTEL2HL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MRHANDYA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MRHANDYB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MRHANDYC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MSTMERCH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MSTRCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTAMBSH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTANT2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTANT3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTANT4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTANT5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTEJAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MUTFRUIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVAIRLOC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVBSHELF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVDWN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVNEWS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVNUKE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVRCRDOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVSCTSHF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MVUP2DWN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 MYSTSTRN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NDEBRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NDWN2UP1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NDWN2UP2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NEAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NECVHOLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NECVLADR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NEIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NGARFRDG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NH2OCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NH2OPUMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHAL2HOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHAL2WAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHAL4HOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHAL4WAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHDN2UP1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHDN2UP2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHDN2UP3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHOT2HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHOT4HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHUP2DN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHUP2DN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NHUP2DN3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NICOLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NUKEGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NUP2DWN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NUP2DWN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWAT2HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWAT4HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWDN2UP1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWDN2UP2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWDN2UP3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWUP2DN1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWUP2DN2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 NWUP2DN3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 OBJ_DUDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ODDWALL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 OFFICER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ORFEO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 OVER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 OVERSEE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 P.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PAINFELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALADINA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALADINB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALADINC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PALSCOUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PATRICK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PAUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PEASANTC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PEASANTD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PEASVICT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PENSMELL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PERNPWR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PETER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PETROX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PEZ.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PHIL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PHRAX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PLEASANT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 POWERMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PRISCON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PRISFELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PRISON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PRISONR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PSYCON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 PSYFIELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADIO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADIOCOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADRAT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADSCAVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADSCOR2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RADSCORP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAIDDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAIDGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAIDMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAIDPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RATION.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RATPIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAYZE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAZLO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RAZOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RD1INIT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RD1KNIG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RD1SCB1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RD1SCRB1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REBEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REDFARM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REDFIELD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REGDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REGGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REGULATR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 REVULSE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RHOMBUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RHOMDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RHOMLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RICHIE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RIPDN2UP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RIPPER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RIPPPRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RIPUP2DN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RN1SCRB1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDCITY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDCOAST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDDERT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDDESRT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDESRT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDECGEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDECSPL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDMERCH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RNDMTN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROAMCLAW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROBCTRL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROBOT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROMERO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROOMGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROPE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ROZBED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUBCHIP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUBCORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUFUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUTGE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 RUTGER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SALLY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SAMMAEL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SAMMY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SAMMY2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SARAH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SAUL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SBOKCASE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCHOLAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCIROOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCOUTC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCOUTF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCRIBEA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCRIBEB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCRIBEC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SCSUPMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SDEBRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SDRESSER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SECDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SECDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SEMICOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SENTRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SENTRYGN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SEST2WST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETCOLER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETDESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETDOOR1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETH2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SETSCTDR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SGENROB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHADDESK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHADYET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHADYRUG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHADYWST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHARK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHED2HAL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SHERRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SINK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SINTHIA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SKIPPY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SKIZZER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SKUMDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SLAPPY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SLUMMER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMELL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMITTY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMONE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMPRAY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SMTWO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SOPDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SOPHIA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SPAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SPOTLITE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SSGUIDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SSRADSCO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SSWELL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STAMPEDE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STAPBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STAPLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STIMPACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STOR2ADY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STOREROM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STRANGER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STUDENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 STUFF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPAMBSH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SUPLYGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SURF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 SWST2EST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TALIUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TALKCOW.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TALKCOWS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TALUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TANDI.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TARDIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TAYLOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TCOWMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TEACHER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TEMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM6.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM7.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERM8.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TERRY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TEST.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TESTER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THERESA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THFD2U.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THFU2D.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THOMAS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THOMAS2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THORNDYK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THSUPMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 THUG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TOGGLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TOLYA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TOW2CHID.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TOWNMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TRAPFLOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TREAD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TRENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TRISH.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TROPHY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TROY.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TYCHO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 TYLIER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 UNDRBED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 USEDCAR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 UTHERN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 UZCHAIR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V132CAVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13CAVE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13CAVES.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13COMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 V13DOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALEL1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALEL2E.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALEL2W.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALEL3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTCORE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTCTZN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTCUPL.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTGLO.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTLEAV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTLOCK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTMED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTMEET.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTMON.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTNEC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTSEC.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VALTSTOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VANCE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VANCEBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VANHAG.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VASQUEZ.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VATALERT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VATSIGN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VATTEAM9.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VATWARN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VAULT13.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VAULTBOX.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VAULTBUR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VAULTENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VBOOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VBROKELV.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VCOMPOP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VCONCOMP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VCONDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VDOORMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VELCTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VEXDTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VFENCEMT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VGATEMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VICTOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VINCENT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VINNIE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VIOLA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VISCIOUS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VLASER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VLOCKER.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VMONOWIR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VPLASMA.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VPLOTMUT.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VPLSTRAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VREE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VREEDISK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VREGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VRESCRIB.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VSGTEAM9.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM1.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM3.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM4.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM5.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM6.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM7.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VTEAM8.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 VWEPLOKR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WANRAT2.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WANRATS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WATRSHED.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WDEBRIS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WEAPSYS.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WHOMAP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WIFE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WIGGUP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMCARVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMGROUP.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMGUARD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMRTNVN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WMVAN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WOMEN.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WOODDOOR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WORKROOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WORLD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRHOLE.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRLADR.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRMGRD.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 WTRTHIEF.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 YOURROOM.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ZACK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ZARK.SSL
IF ERRORLEVEL 1 PAUSE
sslc_f1 ZAX.SSL
IF ERRORLEVEL 1 PAUSE
MOVE /Y *.INT C:\USERS\SDUIBEK\DOCUMENTS\DROPBOX\FALLOUT\DATA\SCRIPTS
IF ERRORLEVEL 1 PAUSE
