procedure start;
procedure description_p_proc;//    script_action == 3


procedure start
begin
	if (script_action == 3) then begin//DETAILED ON-CLICK DESCRIPTION (Binoculars icon) - description_p_proc
		call description_p_proc;
	end
end

procedure description_p_proc
begin
	script_overrides;
	display_msg(message_str(681, 100));
	if (global_var(138) == 1) then begin
		if (is_success(roll_vs_skill(dude_obj, 12, 0))) then begin
			display_msg(message_str(681, 101));
		end
	end
end

